### PR TITLE
Update Included Post “camellia/2023-11-16-discography”

### PR DESCRIPTION
**Pull request by SeddyHacker**
Automatically generated by Decap CMS

### CODE REVIEW

**Review by papertek — CHANGES_REQUESTED** [review]
the spaces stink

**Comment by Aisuruneko** [comment]
> the spaces stink

like you


just kiddinng

**Review by papertek — CHANGES_REQUESTED** [review]
article links must have the ``.md`` file extension in the end

**Review by papertek — APPROVED** [review]
yes

**Pull request merged**
