### PR TITLE
Create Included Post “camellia/guest-appearances/2024-02-06-guestappearances”

### PR DESCRIPTION
**Pull request by KatGrrrl**
Automatically generated by Decap CMS

### CODE REVIEW

**Comment by papertek** [comment]
@Aisuruneko this is an interesting one, can you fix any fuckups from this?

**Comment by papertek** [comment]
@Aisuruneko bump

**Comment by papertek** [comment]
instead of merging this, i have resolved weirdness with [this commit](https://github.com/CamelliaCommunity/Wiki/commit/749b88ac3cf823153efa4670e6a401693945179f)

@KatGrrrl in the CMS, you may want to relocate the updated document as i moved it and renamed it so things could be more sane

**Comment by Aisuruneko** [comment]
please reopen and merge this instead.

**Review by papertek — APPROVED** [review]
yes

**Pull request merged**
